# Generated by Django 2.2.6 on 2019-12-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValidateText', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
